### ISSUE TITLE
关于UI的几个疑问（1.9）

### ISSUE THREAD

**Issue by niokia0v0** [Xinyuell/DspFindSeed#1]
1.六个可选的星球类型是有顺序的吗？比如我指定从左向右从上向下的第一个选项的类型而其他五个不做指定，条件会是“离恒星最近的行星必须是这个类型”吗？
2."是否写矿物数量"是什么意思？

头一次用Issues,不知道是否可以用作提问，也找不到其他联系作者的方式，如有不当之处还请告知m(_ _)m

**Comment by Xinyuell** [comment]
- 没有，是乱序的
- 指输出的log是否写入矿物数量，有的条件只是搜亮度之类的，不关心矿物数量的信息
