### ISSUE TITLE
能加个多线程吗

### ISSUE THREAD

**Issue by Gyxqq** [Xinyuell/DspFindSeed#12]
能加个自定义线程选项吗，感觉服务器128核心没怎么跑满

**Comment by ChZhongPengCheng33** [comment]
> 能加个自定义线程选项吗，感觉服务器128核心没怎么跑满

原版种子算法多线程下有线程安全问题，需要修改才能适应多线程生成

**Comment by Gyxqq** [comment]
这是来自QQ邮箱的自动回复邮件。邮件已收到​
