### ISSUE TITLE
推荐多线程+cuda加速

### ISSUE THREAD

**Issue by Shapaper** [Xinyuell/DspFindSeed#3]
建议程序内置多线程
假如可以加上CUDA多线程（3090TI有10000多个流处理器）

**Comment by Xinyuell** [comment]
我试试

**Comment by Xinyuell** [comment]
> 建议程序内置多线程
> 假如可以加上CUDA多线程（3090TI有10000多个流处理器）

多线程我fork的库，作者用了c#的多线程但效果我测试过并没有多大效率的提高
如果能用GPU处理应该会很快，但我刚搜了一下 cuda是基于c/c++的
因为种子生成相关逻辑都是c#
你有了解有什么第三库可以直接用c#来调用cuda吗

**Comment by Xinyuell** [comment]
> 种子生成的逻辑多吗？

额，确实还不算太多，我之前为了方便，自己私下移植了js，想直接搭个网页搜索共享的。但止步于js的math库运算结果和c#不一样。官方随机用到了16位以上的小数运算结果，js不支持就放弃了。
不过，问题是我不会c 0.0

**Comment by Shapaper** [comment]
C#呢？

**Comment by Shapaper** [comment]
戴森球计划也是基于C#的cuda计算

**Comment by Xinyuell** [comment]
> 戴森球计划也是基于C#的cuda计算

额，这个还是区别挺大的吧。戴森球游戏主要用的unity内的一些插件，例如gpuinstance这种，把大量重复物体交给gpu处理。我现在的游戏项目也会用到这些。但这都是被深度包装并且和unity绑定了的库。

**Comment by Shapaper** [comment]
能不能基于unity引擎制作ui？
顶多安装包大些

**Comment by Xinyuell** [comment]
研究了一下 不太行
