### ISSUE TITLE
二次筛选时能否直接搜索种子+恒星数

### ISSUE THREAD

**Issue by Nemo1166** [Xinyuell/DspFindSeed#4]
如题，现在的算法好像只会读取csv中的种子ID，如果先初筛然后二次搜索还是会遍历32~64恒星。可不可以在导入csv时直接读种子+恒星数？这样可以加快二次筛选的速度。

**Comment by Xinyuell** [comment]
不好意思很久没看这个项目了。一般你筛出来的种子没几个吧，真的有这个需求吗。。不过之前贴吧确实有人问过，我晚点更新一个版本。

**Comment by Xinyuell** [comment]
> 如题，现在的算法好像只会读取csv中的种子ID，如果先初筛然后二次搜索还是会遍历32~64恒星。可不可以在导入csv时直接读种子+恒星数？这样可以加快二次筛选的速度。

已更新
