### ISSUE TITLE
使用运行时无关Random

### ISSUE THREAD

**Issue by sselecirPyM** [Xinyuell/DspFindSeed#5]
将URandom1类的Next函数改为
```
        public int Next()
        {
            if (++inext >= 56)
            {
                inext = 1;
            }
            if (++inextp >= 56)
            {
                inextp = 1;
            }
            int num = SeedArray[inext] - SeedArray[inextp];
            if (num < 0)
            {
                num += 2147483647;//int.MaxValue
            }
            SeedArray[inext] = num;

            if (num >= 1073742080)
            {
                if ((num - 1073742080) % 1024 == 0)
                    return num - 1;
            }
            else
            {
                for (int i = 0; i < 8; i++)
                {
                    int d = 536871040 >> i;
                    int e = 1073741824 >> i;
                    if (num >= d)
                    {
                        if (num < e && (num - d) % (512 >> i) == 0)
                            return num - 1;
                        break;
                    }
                }
            }

            return num;
        }
```
即可
Next(int)和Next(int,int)暂无解决方案，不过本身误差较小。

------------------------------------------------
在Compute Shader中实现Random，运行8,388,608个测试，每个测试调用6次Next，CPU使用原实现，结果无错误。
比较RTX2070-MaxQ i7-9750H， gpu上运行Random加速比可达~~3.5~~ 12倍。

**Comment by sselecirPyM** [comment]
HLSL实现寻找最高恒星亮度的程序，精度全部使用float，加速可达百倍。但是约1%的结果存在较大误差，经测试属浮点精度导致，与同精度CPU算法CPU运行结果相同。

**Comment by Xinyuell** [comment]
> HLSL实现寻找最高恒星亮度的程序，精度全部使用float，加速可达百倍。但是约1%的结果存在较大误差，经测试属浮点精度导致，与同精度CPU算法CPU运行结果相同。

官方精度全用的double，如果存在误差岂不是会导致最终随出来的种子数据不一样？

**Comment by sselecirPyM** [comment]
> 

肯定是不一样的，但是目前只找了恒星的亮度，其他数据是否有较大误差还不清楚。暂时没编写通用的搜索程序。全用double应该也能有比较可观的加速比。

https://github.com/sselecirPyM/DSPSeedFastSearch

另外我看到另外一个issue里你提到了移植到js，所以现在可以做了吗。

**Comment by Xinyuell** [comment]
> > 
> 
> 肯定是不一样的，但是目前只找了恒星的亮度，其他数据是否有较大误差还不清楚。暂时没编写通用的搜索程序。全用double应该也能有比较可观的加速比。
> 
> https://github.com/sselecirPyM/DSPSeedFastSearch
> 
> 另外我看到另外一个issue里你提到了移植到js，所以现在可以做了吗。

也是受制于这个精度问题，js的float精度太低了，算出来的结果不一样。我本来是打算丢网页上用的，但是由于结果不一样我就放弃了
