### ISSUE TITLE
2.8版本种子详情显示目前仍与游戏内不符

### ISSUE THREAD

**Issue by Ranlajetech** [Xinyuell/DspFindSeed#7]
游戏 v0.9.26.13034
种子搜索器 v2.8 (Pre-release)
测试用种子: 29366
星区恒星数: 64
资源倍率: 无限
恒星系: Beta Draconis (O型恒星)
测试条件: 沙盒模式
问题详情: 使用种子搜索器写出单个种子详细，csv文件中列出该星系存在光栅石矿脉，而游戏中实际上不存在；行星种类也存在偏差，csv文件显示该星系V号星（第四行星）为飓风石林，而游戏中为黑石盐滩。
![csv](https://user-images.githubusercontent.com/56589757/180483824-4080cb87-fad2-4e2d-bb2f-42b84ce3d8b2.jpg)
![gamestar](https://user-images.githubusercontent.com/56589757/180484139-5b6cf2a8-3c4c-4579-94d2-d9b2037e4c27.jpg)
![gameV](https://user-images.githubusercontent.com/56589757/180483974-4db45eca-a8f2-4dd6-bead-577edd9331b4.jpg)

**Comment by Xinyuell** [comment]
现在应该好了，没问题我关issue了

**Comment by Ranlajetech** [comment]
fixed
